{% set name = "jsonextended" %}
{% set version = "0.7.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8044ddc359c8ff91b5b3183be33822131bfddf85ddcc2fd91640029b2c51464a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pathlib2
    - pip
    - python
  run:
    - ijson
    - pathlib2
    - pint
    - python

test:
  imports:
    - jsonextended
    - jsonextended.encoders
    - jsonextended.parsers
    - jsonextended.units

about:
  home: https://github.com/chrisjsewell/jsonextended
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: Extending the python json package functionality
  doc_url: https://jsonextended.readthedocs.io
  dev_url: https://github.com/chrisjsewell/jsonextended

extra:
  recipe-maintainers:
    - chrisjsewell
