travis:
  secure:
    BINSTAR_TOKEN: FQ5JwKponGaRbn4n6u1vc8h+4ovL2YBomnbWb8XX8wUWwhRZpR5eovCUOb/lRfR0HrFGcJWUfRevywMwGOhqzEOq//9SiMUIx53+BQw/13mP+7MZYBy9iU/Vbz25gQDYc0eA7eINX+fLOIzWF3I+TksY8VpmglBO5Qk/2zJfhZMhBWHHdhEhzdMo8u0cEDiChukiOVpQdK+uougqVtBtqh/mgL8cDhkXWq+1lHKpvbiYV0iuJ/sCaD1mbTWaLn8Ru3vV6clg13brBvszDEGTwY0aKMpKUh4JpFTqOh8rPmCVEpCZ6ZhzHH/odie2wd/CiQ9bw6NxVzrXZrDtlCcHJHTPMP50xlCYr3+OwwEGF6148VKM2k2CdEaB73nUPLugRBPzy5nwuo4hC+BTS8wI4Wfj8/jVhvfRdY9k1OsWqR7dmSfzzc8+Aeeq0mgiOo8w43KKzcYzf/btVc4j17lt+2fD9keN63/z+SdA3ZVTiy6LFS+OZbu8y2APQUBUz1mz5Q3Wb1Nlvightez1oZGGvFJM/qUrYMcv2cg1TJEZIdYvcIWEVBl/pCz7iXpdMujeZGlnp0X9ED46lbDJ5ix/bMLg2VqnFmOkF7lqt4x5HQ+QHwabHLMpYDT6nrdOo2MdFlqxYM77V6Sq8ZLkYYIo5A83rR2VJWHYSMtLT+t5qjY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
