travis:
  secure:
    BINSTAR_TOKEN: LJ+AJxiJKQx9siQ6wnbRADWw694lzPhamASIdNNARFzoF+DSCbeiDNJe8YB2OlXEMszcQbv28O/rPnFh1LuLx5x71ys1gq1qs4XSRIB3KjII2Mr21MEa1nccDRsAfVeUB4GlS4awDXmWj5lE3KoZ8NbzKkmPwj1Z5mPZBKjwwmowT08gvm5MZKCgHgytyaNAbx3YIpLiCXaTMBm6rfgEmAj5KR7+V3Ix6W35ej25ZnTsQuxzl1ZfrQ0MVjkw1uAe2jZ6wlxkpP4pGqn0oyyFDIzaP00gewNBklXe7XJ/TCpYcbEzyCVq9E8ohPJAHBz+9P4p0c/T6/wkw9UNKbF8A2SVCr6EfGpCmmeW+/wKoyOm24SolPKLaZZlE/GVkWzVcvpgBTBXiSyCC0rBxcLmgSUthygYLX/M9elMwaYoD5Jc9BgJEw9Pw+X5HkbF0C2P0bs4i7arCYgxSdRIyl+CKUkraUdoYMSM912mvg4VOPOOssxfWrREvvjTLGMMtXJJcKnynXVcDLhLgmEfo0RkLx/sQcUglVofaS+yWAP9K4AyOzyxvwAZY24cTek5W3JKmCD0181PAUsLCiM805CmDH4AE+rvKZ/JLNqgwEvAPVsmiywNhPEmUS9IlzHC1BEUgyqBWe8seLToLzYPR6zrRP7C+jgaZXOFfFOW1Bf/j0k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
